import os
level0 = [
	"           d       ",
	"           d       ",
	"           d       ",
	"           d       ",
	"           d       ",
	"           d       ",
	"           d       ",
	"           d                          m ",
	"  	        d     m                  gggg",
	"           d   ggg          M       dddd",
	"  	        d               ggm 2      dd            ",
	"           d    2       mggddgggm     dd            ",
	"        m  m  m   m  m mgdddddddgg  m     m    m    ",
	"ggggggggggggggggggggggggddddddddddgggggggggggggggggg",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd",
	"dddddddddddddddddddddddddddddddddddddddddddddddddddd"]
level1 = [
".................................................................................................................................................q.....",
"...............................................................................................................................................qqQqq...",
".............................................................................................................................................qqQQQQQqq.",
"..................................................................................................................cccccccc..................qQQQQCQQQQq",
"..........................................................................................................................ccccc.............qqqqqqqqqqq",
".............................................................................................................................................pPpp.ppPp.",
".............................................................................................................................................pPpp.ppPp.",
".............................................................................................................................................pPpp.ppPp.",
"............................................................................................................................................qqqqqqqqqqq",
"...................................................................cccc..............................................................gggggggddddddddddd",
"................................................................ccc..x............................................................gggddddddddddddddddds",
".....................................................................x.......................................................gggggdddddddddddssssssssss",
".....................................................................x...................................ggggggggggggggggggggddddddddddddssssssssssssss",
".....................................................................x....................gggggggggggggggdddddddddddddddddddddddddsssssssssssssssssssss",
".....................................................................x..........ggDDDgggggdddddddddddddddddddddddddssssssssssssssssssssssssssssssssssss",
".....................................................................x.....gggggddDDDddddddddddddddddddddddssssssssssssssssssssssssssssssssssssssssssss",
"..........................................................q..........x..gggddddddDDDddddddddddddddsssssssssssssssssssssssssssssssssssssssssssssssssssss",
".......ccc..............................................qqQqq........xggddddddddDSSSsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"..........cccc........................................qqQQQQQqq......gddssssssssSSSssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
".....................................................qQQQQCQQQQq.....ddssssssssSSSsssssssssssssDsssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"gggggg..2............................................qqqqqqqqqqq.....sssssssssSSSSsssssssssssDDDsssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ddddddggggwwwwwwwwwwww................................pPpp.ppPp......sssssssssSSSsssssssssssssDDsssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ddddddddddddwwwwwwdddw........3.......................pPp...pPp.....sssssssssSSSSssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ddddddddDDDddddddddD.w........3.......................pPpW.WpPp.....sssssssSSSSSsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"dddddddDDDDDDDDddDDD.w........3.....................mqqqqqqqqqqq....ssssssSSSSSssssDDDDssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sdsssdsDSDDDSDDDDDS..w........3.....................gdddddddddddg...SSSSSSSSSsssssDDDDsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ssssssSSSSSSSSSSSSS..w...........................mggdddddddddddddg..SSSSSSSssssssssDDDsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ssssssSSSSSSSSSSSSS..w..........................ggddddddddddddddddggsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ssssssssSSSSSSSSSSs..w........M..m...m......m..gddddddddddddddddddddsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssawwwwwwaagggggggggggggggggggdddddddddddddddddsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ssssssssssssssssssssawwwwaddddddddddddddddddddddddddddddddddddsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssaaaaddddddddddddddddddddddddddddddddddssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"ssssssssssssssssssssssssddsssdssssdssdsssssssdssssssdsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",
"sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss",]
level1b = [
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..................qqqq",
"qqqq..qqqqqqqqqqqqqq..qqqq",
"qqqq..PPP........PPP..qqqq",
"qqqq..PPP........PPP..qqqq",
"qqqq..PPP........PPP..qqqq",
"qqqqMMPPP........PPPMMqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqqq",
"qqqqqqqqqqqqqqqqqqqqqqqqq",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"....................",
"............2..........",
]
sound = 1.0
path = os.path.dirname(os.getcwd())+"/plat.platformer/Assets/"
Backgrounds = {0:path+"sky.png",1:path+"sky.png", 1.1:path+"skydark.png", 1.2:path+"snowSky.png"}
tilesize = 40
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

